### ISSUE TITLE
[Mobile] Visitor melihat catalog product

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#1]
CEK : https://trello.com/c/dfyeEUNa/179-2-visitor-melihat-catalog-melalui-phone-tablet
- HOME
- [x] Section new release , ketika ada diskon urutan tidak rapi (
  ![screenshot_2016-09-03-10-31-06](https://cloud.githubusercontent.com/assets/5895063/18222433/d7ad2cc4-71c1-11e6-9dae-8b0b5b2932c2.jpg)
- [x] Section Instagram tidak bisa di klik
- [x] Menu footer tidak ada ? (Q), How can I contact balin?
- [x] Apa yang terjadi jika shopping bag kosong ? Adakah rekomendasi ? (Q)
- [x] Ketika loading tampilan messed up (
  ![screenshot_2016-09-03-10-31-06](![screenshot_2016-09-03-10-00-30]%28https://cloud.githubusercontent.com/assets/5895063/18222471/a39f08c0-71c2-11e6-8fb4-b5629d925c84.jpg%29)
- Product
- [x] Ketika berada di section wanita, navbar shortcut wanita tidak menyala
- [x] Apa yang terjadi jika shopping bag kosong ? Adakah rekomendasi ? (Q)
- [x] Filter kadang macet 
- [x] Tidak ada clear all filter 
- [x] Tidak ada menu sort by (
  ![screenshot_2016-09-03-10-05-09](https://cloud.githubusercontent.com/assets/5895063/18222478/b9fafc5a-71c2-11e6-9ca5-09c0d30933ac.jpg)
  ) 
- [x] Jumlah produk 3 ketika tidak ada hasil pencarian, ketika di mobile agak aneh (kanannya kosong)
- Product Detail
- [x] Ketika berada di section wanita, navbar shortcut wanita tidak menyala
- [x] Margin content tidak sama dengan margin navbar (
  ![screenshot_2016-09-03-10-22-43](https://cloud.githubusercontent.com/assets/5895063/18222481/c9165108-71c2-11e6-9383-9c7a48463a5c.jpg)
  )

**Comment by agilma** [comment]
@chelsymooy : Menu footer tidak ada ? (Q), How can I contact balin
me : masuk di menu navbar kiri

@chelsymooy : Apa yang terjadi jika shopping bag kosong ? Adakah rekomendasi ?
me : tidak bisa buka shopping bag, dan tidak ada rekomendasi untuk mobile

ketika loading tampilan messed up, untuk list issue ini minta di upload ulang imagenya soalnya tidak kelihatan @chelsymooy

**Comment by budi7** [comment]
Ketika loading tampilan messed up
done : 015927b

**Comment by budi7** [comment]
Margin content tidak sama dengan margin navbar
-> pertimbangan menu terlalu mepet ke kiri layar, serta jarak dengan icon balin tidak seimbang antara kiri dan kanan jika icon menu(kiri) digeser mendekati tepi kiri.

**Comment by budi7** [comment]
Tidak ada clear all filter
A: filter sudah diletakkan dalam section filter
![screen shot 2016-09-14 at 3 36 46 pm](https://cloud.githubusercontent.com/assets/10555410/18505383/2b640fae-7a91-11e6-8ee6-e0885878adb1.png)

**Comment by budi7** [comment]
Filter kadang macet
 A : Muncul pesan error saat request ajax gagal.
