### ISSUE TITLE
Need filter by gender

### ISSUE THREAD

**Issue by budi7** [ThunderID/BALIN-WEB-V2#10]
can't filter man/woman collection only
![screen shot 2016-09-05 at 10 32 41 am](https://cloud.githubusercontent.com/assets/10555410/18236861/08adec48-7355-11e6-80de-04a51b4f7267.png)

**Comment by chelsymooy** [comment]
gmn kalau yang atas di klik pun filternya gak berubah cuma nambah kategori?
