### ISSUE TITLE
[Tablet] 27. Visitor melihat catalog

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#11]
Check : https://trello.com/c/O2XRG4hp/209-27-visitor-melihat-catalog-melalui-tablet
- Home
- [x] Ketika portrait, section by style nya stretching (
  ![img_2793](https://cloud.githubusercontent.com/assets/5895063/18239081/f4e0d8f2-736c-11e6-9483-498a57a5091a.PNG)
  )
- [x] Ketika portrait, tidak ada menu di footer sementara di header tidak ada pilihan kategori pria/wanita (
  ![img_2795](https://cloud.githubusercontent.com/assets/5895063/18239097/14b966a8-736d-11e6-99d5-14e9cd211376.PNG)
  )
- [x] Ketika landscape, kategori pria dan wanita keluar dari navbar (
  ![img_2794](https://cloud.githubusercontent.com/assets/5895063/18239116/36fca1d0-736d-11e6-9281-3385403a9857.PNG)
  )
- [x] Ketika portrait, jumlah item shopping bag tidak terlihat (gambar checklist 3)
- Collections
- [x] Ketika portrait, tidak ada menu di footer sementara di header tidak ada pilihan kategori pria/wanita
- [x] Ketika landscape, kategori pria dan wanita keluar dari navbar[DUPLICATE]
- [x] Ketika portrait, jumlah item shopping bag tidak terlihat [DUPLICATE]
- [x] Ketika portrait, filternya terlampau besar (
  ![img_2796](https://cloud.githubusercontent.com/assets/5895063/18239129/4b727ed2-736d-11e6-82fd-0ff6223a8b4e.PNG)
  )
- Collection Detail
- [x] Ketika portrait, tidak ada menu di footer sementara di header tidak ada pilihan kategori pria/wanita 
- [x] Ketika landscape, kategori pria dan wanita keluar dari navbar [DUPLICATE]
- [x] Ketika portrait, jumlah item shopping bag tidak terlihat [DUPLICATE]

**Comment by budi7** [comment]
Ketika portrait, tidak ada menu di footer sementara di header tidak ada pilihan kategori pria/wanita
A: mengikuti desain mock up yang @chelsymooy diberikan. jika ingin ditampilkan, dibutuhkan mock up baru, karena untuk ukuran portrait section footernya kekecilan

**Comment by budi7** [comment]
Ketika landscape, kategori pria dan wanita keluar dari navbar
-> Tested : no problem by @chelsymooy

**Comment by budi7** [comment]
Ketika portrait, section by style nya stretching 
-> Tested : no problem by @chelsymooy

**Comment by chelsymooy** [comment]
Ketika portrait, section by style nya stretching 

mas @budi7  : iya , kapan hari diganti class tile-nya
lupa centang ^^'

**Comment by chelsymooy** [comment]
Ketika portrait, section by style nya stretching 

mas @budi7  : iya , kapan hari diganti class tile-nya
lupa centang ^^'
