### ISSUE TITLE
Premature email saving on signup

### ISSUE THREAD

**Issue by budi7** [ThunderID/BALIN-WEB-V2#12]
kasus: signup -> daftar dengan email baru, namun password tidak match hanya di-isi 4 char -> redirect back with error msg : password min 8 digits -> benerin password -> muncul pesan error email sudah disimpan
1. 
![screen shot 2016-09-05 at 1 39 12 pm](https://cloud.githubusercontent.com/assets/10555410/18239292/7fc065b8-736e-11e6-8f0c-7e13c2ee0ba7.png)
2. 
![screen shot 2016-09-05 at 1 39 22 pm](https://cloud.githubusercontent.com/assets/10555410/18239291/7fbef976-736e-11e6-8b27-77eb342b4fe8.png)
3.
![screen shot 2016-09-05 at 1 39 30 pm](https://cloud.githubusercontent.com/assets/10555410/18239293/7fc12746-736e-11e6-9a39-7c33a655137a.png)

**Comment by chelsymooy** [comment]
Ini issuenya di front end
required min 4 itu punya frontend

**Comment by chelsymooy** [comment]
Ini issuenya di front end
required min 4 itu punya frontend (Q)
