### ISSUE TITLE
[Tablet] 28. Customer melihat catalog

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#13]
CEK : https://trello.com/c/spBbXFFx/210-28-customer-melihat-catalog-melalui-tablet

Extend from issue : https://github.com/ThunderID/BALIN-WEB-V2/issues/11
- Home, \* Collections, \* Collection detail
- [x] Tidak ada menu dropdown untuk 'my' section (profile, sales, point, dll) - both landscape & portrait
  (
  ![img_2803](https://cloud.githubusercontent.com/assets/5895063/18239530/1413b278-7370-11e6-81da-6bdde690b9cc.PNG)
  )
  (
  ![img_2804](https://cloud.githubusercontent.com/assets/5895063/18239535/1b6696e4-7370-11e6-9b36-607380a716a3.PNG)
  )
- [x] Jika user login, apakah menu balin point menjelaskan tentang balin atau menjelaskan tentang point dan redeem? (Q)
- Collection detail
- [x] Portrait, Pada preview gambar collection, anak panah next & prev keluar dari margin (
  ![img_2805](https://cloud.githubusercontent.com/assets/5895063/18239542/20af8368-7370-11e6-8031-a4af8a28c315.PNG)
  )

**Comment by budi7** [comment]
Tidak ada menu dropdown untuk 'my' section (profile, sales, point, dll) - both landscape & portrait.  
Q : Karena DI versi Desktop juga tidak ada, maka di tablet juga menyesuaikan. mungkin yang ditambahkan adalah utk section produk pria dan wanita. @chelsymooy

**Comment by budi7** [comment]
Tidak ada menu dropdown untuk 'my' section (profile, sales, point, dll) - both landscape & portrait
update : #11 - 83a02fc
