### ISSUE TITLE
[Tablet] 29. Customer menambahkan produk ke keranjang

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#14]
CHECK : 
https://trello.com/c/iLjJjHKC/211-29-customer-menambahkan-produk-ke-keranjang-via-tablet
- Collection detail
- [x] subtotal ketika ada diskon tidak valid. Subtotal = promo price \* qty if promo price != 0 (
  ![img_2806](https://cloud.githubusercontent.com/assets/5895063/18239696/277ea560-7371-11e6-89ee-fec082ee00b8.PNG)
  )
- Cart Index
- [x] Undefined index varians (
  ![img_2807](https://cloud.githubusercontent.com/assets/5895063/18239699/359a3b28-7371-11e6-9d80-1910173d7717.PNG)
  )

**Comment by budi7** [comment]
@chelsymooy case nya karena issue #24 kah utk yg undefined varians?

**Comment by budi7** [comment]
@chelsymooy, masalahnya dimana ini kok di open lagi?

**Comment by chelsymooy** [comment]
mas @budi7 yang masalah harga coret & harga diskon itu
