### ISSUE TITLE
[Tablet] 30. Visitor menambahkan produk ke keranjang

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#15]
Check : 
https://trello.com/c/U4FFsl6Z/212-30-visitor-menambahkan-produk-ke-keranjang-via-tablet
Similar Issue :
https://github.com/ThunderID/BALIN-WEB-V2/issues/14
- Shopping Bag Index
- [x] Kesalahan perhitungan total / item. Diskon = price - promo price if promo price > 0
  (
  ![img_2809](https://cloud.githubusercontent.com/assets/5895063/18239951/d6f3517a-7372-11e6-83c2-65b69b721395.PNG)
  ) 
- [x] Ketika max quantity, button + masih berwarna hitam (prev image)
- [x] Ketika portrait, posisi button + tidak tepat
  (
  ![img_2810](https://cloud.githubusercontent.com/assets/5895063/18239961/e5735eca-7372-11e6-9c64-46217e5ad1c0.PNG)
  )
- [x] Link shopping bag not working

**Comment by budi7** [comment]
Doing . . .
