### ISSUE TITLE
[Tablet] 33. Visitor Mendaftar ke balin

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#16]
- Cek : https://trello.com/c/Q4iux5WZ/215-33-visitor-mendaftar-ke-balin-via-tablet
- Sign Up
- [x] Ketika portrait, tidak ada pilihan sign up (dan landing page = login)
- [x] Ketika landscape, button daftar menggunakan facebook captionnya terpotong
- [x] Ketika portrait, ada white space antara navbar dan background
- [x] Pesan error tidak berwarna merah

**Comment by budi7** [comment]
Fix : Ketika portrait, ada white space antara navbar dan background
On :    #17 - 391242b

**Comment by budi7** [comment]
Q :  Pesan error tidak berwarna merah
No problem detected, maybe test the old version ? @chelsymooy 
![screen shot 2016-09-06 at 5 57 55 pm](https://cloud.githubusercontent.com/assets/10555410/18271287/8b3a537a-745b-11e6-9333-bbf024bc6b67.png)
