### ISSUE TITLE
[Tablet] 38. Customer lupa password

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#18]
Check :
https://trello.com/c/yXKIlYVW/220-38-customer-lupa-password-via-tablet
- Forgot Password
- [x] Ketika portrait, ada whitespace antara header dan background
- [x] Ketika portrait, ada whitespace antara footer dan end of window
- Change Password
- [x] Ketika portrait, ada whitespace antara header dan background
- [x] Ketika portrait, ada whitespace antara footer dan end of window

**Comment by budi7** [comment]
need check on native device @chelsymooy
