### ISSUE TITLE
return Voucher

### ISSUE THREAD

**Issue by budi7** [ThunderID/BALIN-WEB-V2#2]
- [x] user insert random voucher and get return success
- [x] typo in success return message
  ![screen shot 2016-09-03 at 12 05 03 pm](https://cloud.githubusercontent.com/assets/10555410/18222872/1ae031e6-71cf-11e6-8f15-0ffd23070791.png)

**Comment by chelsymooy** [comment]
First check-list checked at : https://github.com/ThunderID/BALIN-API-V2/commit/5c4758cc22fff2a5e063af0dfd9fd80c86923207
