### ISSUE TITLE
[Desktop] Visitor melihat catalog melalui pc

### ISSUE THREAD

**Issue by agilma** [ThunderID/BALIN-WEB-V2#21]
check : 
https://trello.com/c/B5tq4lSX/178-1-visitor-melihat-catalog-melalui-pc
## Home

**Logo balin**
- [x] **[question]** logonya agak blur gak seimbang dengan menu navigasi, apa diseragamin?

![screen shot 2016-09-05 at 3 32 38 pm](https://cloud.githubusercontent.com/assets/4099329/18241929/0eae59f6-737e-11e6-873b-c7f17012467b.png)
- [x] **[question]** huruf r kecil dikanan kayaknya menganggu? apa dihilangkan?
  **header wanita/pria**
- [x] **[enhanment]** kalau hover tidak ada perubahan apa, dan kalau aktif gambar wanita atau prianya tidak sama dgn warna orange

![screen shot 2016-09-05 at 3 34 22 pm](https://cloud.githubusercontent.com/assets/4099329/18242839/755b1b22-7382-11e6-9c43-1c6b8a929f8f.png)

**header balin point**
- [x] **[question]** apa mungkin dibuat warna yang brbeda biar menarik untuk lari kesana?
- [x] **[bug]** untuk balin point content masih dummy text

**shop by style**
- [x] **[bug]** error link masih menuju localhost untuk preppy & 20s birthday

**rekomendasi dropdown**
- [x] **[enhanment]** untuk sizenya baju tidak ada 
- [x] **[enhanment]** warna coret harganya tidak sama dengan di product

**footer**
- [x] **[enhanment]** cara pembayaran & jasa pengiriman blm bisa dklik
- [x] **[bug]** untuk di keep in touch link instagram error, sepertinya akun balin usernamenya berubah
- [x] **[enhanment]** bedakan warna footer label dgn link
## Collection

**sub menu category**
- [x] **[question]** multiple category? 

**filter**
- [x] **[bug]** tanda filter aktif untuk color tidak ada

![screen shot 2016-09-05 at 4 09 34 pm](https://cloud.githubusercontent.com/assets/4099329/18243010/321ed24e-7383-11e6-81f4-f9d73a9eaa2f.png)
- [x] **[bug]** saya pilih slimfit, cotton, work outfit muncul batik, tapi setelah klik lengan panjang item muncul, lengen pendek item juga muncul, tapi jika kedua panjang dan pendek di klik item sebelumnya malah tidak muncul itemnya
- [x] **[bug]** tidak ada page eror atau page tidak ada jika

![screen shot 2016-09-05 at 4 11 33 pm](https://cloud.githubusercontent.com/assets/4099329/18243060/7bf6adf6-7383-11e6-8b93-aeeff11e13fa.png)
- [x] **[bug]** rekomendasi item disaat kita pilih category pria, yang keluar rekomendasi wanita

![screen shot 2016-09-05 at 3 04 13 pm](https://cloud.githubusercontent.com/assets/4099329/18243093/a1903d02-7383-11e6-87a1-20b5b121d23e.png)

**pagination**
- [x] **[enhanment]** link next & previous tidak sesuai dgn yg di mockupnya rekomendasi product
## Collection detail

**active category**
- [x] **[bug]** tidak ada tanda active category 

**stock logic**
- [x] **[questions]** perlukah ada notif jika di tambahkan sampai stock maximal?

**section other**
- [x] **[enhanment]** di section pilihan lain link hover colornya tidak ada
  ![screen shot 2016-09-05 at 3 22 36 pm](https://cloud.githubusercontent.com/assets/4099329/18243334/e34575ae-7384-11e6-8dd6-b8e75d074f16.png)

**isi shopping bag**
- [x] **[bug]** misal kita lagi buka description terus tiba2 klik buy now, tidak ada tanda apa2, sepertinya perlu notif untuk menambahkan sizenya, tidak ada notif stock blm ditambahkan
  ![screen shot 2016-09-05 at 4 24 43 pm](https://cloud.githubusercontent.com/assets/4099329/18243452/4d8a04fc-7385-11e6-8671-52fe0b7454f1.png)
- [x] **[question]** untuk buy now misal kita add size 8 baru add size 6 di cart, tidak urut sesuai size melainkan siapa yang di add terlebih dahulu
  ![screen shot 2016-09-05 at 1 14 30 pm](https://cloud.githubusercontent.com/assets/4099329/18243488/6e5dec0c-7385-11e6-9a6c-4839ee6f8901.png)
- [x] **[bug]** notif cart muncul tidak bisa close setelah add product, agak susah jika itemnya banyak dan menutupi     button 'buy now'
  ![screen shot 2016-09-05 at 1 16 24 pm](https://cloud.githubusercontent.com/assets/4099329/18243505/7dd20100-7385-11e6-8463-5fb18fd45e93.png)
- [x] **[bug]** memasukkan item 4 menu shopping bag melewati dan tidak bisa masuk ke cart ataupun checkout
  ![screen shot 2016-09-05 at 1 16 49 pm](https://cloud.githubusercontent.com/assets/4099329/18243517/892099b8-7385-11e6-8d91-5b78686203c9.png)

**Comment by chelsymooy** [comment]
mas @uchuy77  
q : huruf r kecil dikanan kayaknya menganggu? apa dihilangkan? header wanita/pria 
a : coba tanya mas2 designer bisa diilangin ga?

**Comment by budi7** [comment]
@chelsymooy 
[question] huruf r kecil dikanan kayaknya menganggu? apa dihilangkan? header wanita/pria
a : menurutku tidak perlu dihilangkan karena ittu ada artinya registered, jadi brand & logo itu uda registered/ dipatenkan. So, menurutku itu bukan lagi masalah desain, tp uda fungsional sih.

**Comment by budi7** [comment]
@uchuy77 
[bug] misal kita lagi buka description terus tiba2 klik buy now, tidak ada tanda apa2, sepertinya perlu notif untuk menambahkan sizenya, tidak ada notif stock blm ditambahkan
a: bukan bug, karena tidak ada item yang ditambahkan ke cart. Namun, belum ada indikator, kalau button tidak memproses apapun karena tidak ada jumlah item yang akan dibeli. 
solution : add indicator saat klik buy now jika tidak ada item dipilih.

**Comment by agilma** [comment]
[bug] tanda filter aktif untuk color tidak ada https://github.com/ThunderID/BALIN-WEB-V2/commit/e7491155a6f0f39d7a35b11c21c4cf8642c5a505

**Comment by chelsymooy** [comment]
@budi7 
Q : huruf r kecil dikanan kayaknya menganggu? apa dihilangkan? header wanita/pria
a : maksudnya itu nanya ke designer dampak hilang/ada

**Comment by budi7** [comment]
Q : perlukah ada notif jika di tambahkan sampai stock maximal?
A : tidak karena sudah di representasikan dengan tombol disable

**Comment by chelsymooy** [comment]
error link masih menuju localhost untuk preppy & 20s birthday
A : Tergantung input

**Comment by chelsymooy** [comment]
rekomendasi item disaat kita pilih category pria, yang keluar rekomendasi wanita
A : https://github.com/ThunderID/BALIN-WEB-V2/commit/d4aaf89ba7400299b56c6c8ce71ad4212e98f843

**Comment by chelsymooy** [comment]
saya pilih slimfit, cotton, work outfit muncul batik, tapi setelah klik lengan panjang item muncul, lengen pendek item juga muncul, tapi jika kedua panjang dan pendek di klik item sebelumnya malah tidak muncul itemnya

A : Jika 2 tag yang dipilih maka dianggap memiliki kedua2nya (Lebih baik gunakan radio button untuk filter yang parentnya sama)
@uchuy77 PENTING

**Comment by chelsymooy** [comment]
cara pembayaran & jasa pengiriman blm bisa dklik
A : Tidak ada link

**Comment by chelsymooy** [comment]
untuk di keep in touch link instagram error, sepertinya akun balin usernamenya berubah
A : iya, balin ganti alamat insta, diatur di store setting

**Comment by chelsymooy** [comment]
untuk balin point content masih dummy text
A : Sesuai input store setting

**Comment by budi7** [comment]
Q: apa mungkin dibuat warna yang brbeda biar menarik untuk lari kesana?
A: menurut saya tidak, krn cukup mendistraksi sehingga kekurangan kesan elegant menurut saya.

**Comment by budi7** [comment]
Fixed : [enhanment] kalau hover tidak ada perubahan apa, dan kalau aktif gambar wanita atau prianya tidak sama dgn warna orange 
Q: siapa yang kerjain tulung di sertakan commit id. thanks
