### ISSUE TITLE
[Desktop] Customer menambahkan produk ke keranjang via pc

### ISSUE THREAD

**Issue by agilma** [ThunderID/BALIN-WEB-V2#23]
Checking : 
https://trello.com/c/Daml7H0V/182-8-customer-menambahkan-produk-ke-keranjang-via-pc
## Route collection detail

**varian max quantity**
- [x] **[question]** add varian item max kemudian add varian item max tidak ada notif yang muncul info varian max
## Route shopping bag index

**varian max quantity**
- [x] **[bug]** varian max btn plus dklik, tetapi total tetap subtotal yang berubah

![screen shot 2016-09-05 at 6 55 42 pm](https://cloud.githubusercontent.com/assets/4099329/18247479/076947b8-739d-11e6-84eb-5793b3bb5143.png)

![screen shot 2016-09-05 at 6 55 48 pm](https://cloud.githubusercontent.com/assets/4099329/18247505/225226a8-739d-11e6-8a08-09dcd7fd3b0d.png)
- [x] **[bug]** varian plus & min, beda varian total sesama varian ikut berubah

![screen shot 2016-09-05 at 6 57 29 pm](https://cloud.githubusercontent.com/assets/4099329/18247534/3f5373b0-739d-11e6-9043-b13ea82f3005.png)
![screen shot 2016-09-05 at 6 57 34 pm](https://cloud.githubusercontent.com/assets/4099329/18247543/509f5152-739d-11e6-9d2d-f55ccbb4f32f.png)

**pengurangan/penjumlahan quantity**
- [x] **[bug]** total harga tidak sesuai dengan yang ditambahkan atau dikurangkan
- [x] **[bug] [question]** ketika mengurangi quantity, lalu reload terjadi seperti ini, ketika proses pengurangan terpotong
  ![screen shot 2016-09-05 at 7 06 18 pm](https://cloud.githubusercontent.com/assets/4099329/18247626/a8c0cb40-739d-11e6-9946-805f8a0945d0.png)
- [x] **[bug] [question]** ketika mengurangi quantity, lalu reload kembali terjadi seperti ini
  ![screen shot 2016-09-05 at 7 09 24 pm](https://cloud.githubusercontent.com/assets/4099329/18247634/b855b656-739d-11e6-9944-78b86317080e.png)

![screen shot 2016-09-05 at 7 09 51 pm](https://cloud.githubusercontent.com/assets/4099329/18247636/bf3686ee-739d-11e6-9680-bd9af2d75cea.png)

**perubahan jumlah bayar**
- [x] **[bug]** hasil tidak sesuai dengan jumlah quantitas

**other**
- [x] **[bug]** ketika item semua dihapus dari shopping bag
  ![screen shot 2016-09-05 at 7 12 19 pm](https://cloud.githubusercontent.com/assets/4099329/18247655/e346a1c2-739d-11e6-9c61-12fbb2cf283d.png)
- [x] **[question]** apakah nama harus disamakan dengan shopping bag?

![screen shot 2016-09-05 at 7 00 34 pm](https://cloud.githubusercontent.com/assets/4099329/18247676/f8885be8-739d-11e6-9487-35e705904db7.png)

![screen shot 2016-09-05 at 7 00 40 pm](https://cloud.githubusercontent.com/assets/4099329/18247681/ffeeedca-739d-11e6-9173-94c473de2709.png)

**Comment by chelsymooy** [comment]
mas @uchuy77 :  apakah nama harus disamakan dengan shopping bag?
a : Iya

**Comment by chelsymooy** [comment]
mas @uchuy77 : persoalan cart itu di cartcontroller nya, aku di un-assignee ya

**Comment by chelsymooy** [comment]
add varian item max kemudian add varian item max tidak ada notif yang muncul info varian max
A : diwakili button + disabled

**Comment by chelsymooy** [comment]
mas @uchuy77 maksud yang ini : 
'varian plus & min, beda varian total sesama varian ikut berubah'

**Comment by chelsymooy** [comment]
mas @uchuy77 
 total harga tidak sesuai dengan yang ditambahkan atau dikurangkan

Waktu tes work fine
Casenya gmn?

**Comment by budi7** [comment]
closed :  [bug] varian plus & min, beda varian total sesama varian ikut berubah
Continue : #27

**Comment by budi7** [comment]
closed : [bug] total harga tidak sesuai dengan yang ditambahkan atau dikurangkan
Continue : #27

**Comment by agilma** [comment]
[tanya] mas @uchuy77 maksud yang ini : 
'varian plus & min, beda varian total sesama varian ikut berubah'

[jawab] itu ada 1 product cart yg masing2 mempunya 2 atau lebih varian, pas waktu nambah/kurang varian salah satu, ke semua varian totalnya ikut berubah, seharusnya total ketiga itu berbeda, sudah di fix-in oleh @budi7

**Comment by chelsymooy** [comment]
mas @budi7 : maksudnya bugs yang disini di pindah ke #27 ?

**Comment by budi7** [comment]
@chelsymooy  pindah #27 utk : 
closed : [bug] total harga tidak sesuai dengan yang ditambahkan atau dikurangkan
closed : [bug] varian plus & min, beda varian total sesama varian ikut berubah

**Comment by chelsymooy** [comment]
oke
