### ISSUE TITLE
Balin Point

### ISSUE THREAD

**Issue by budi7** [ThunderID/BALIN-WEB-V2#35]
- [x]   tidak ada info baik itu error atauppun sukses setelah memasukkan referal code

![screen shot 2016-09-19 at 10 55 44 am](https://cloud.githubusercontent.com/assets/10555410/18622329/d18dca5e-7e57-11e6-83f1-342c71617699.png)

**Comment by agilma** [comment]
561d4b627d30774409b17e3d3bd88facd88ff9c7
