### ISSUE TITLE
redeem page

### ISSUE THREAD

**Issue by agilma** [ThunderID/BALIN-WEB-V2#36]
- [x] waktu inputkan redeem code yang terdaftar atau redeem code kepunyaan sendiri, tidak muncul sesuatu info atau notifikasi kalau error atau info gagal memasukkan redeem code
  ![screen shot 2016-09-16 at 2 47 56 pm](https://cloud.githubusercontent.com/assets/4099329/18622386/ac5d9bc8-7e58-11e6-9943-f860cb8a224a.png)
- [x] waktu bagikan via email, setelah input email lalu klik kirim tidak ada info sudah terkirim atau salah mengirim kode referal
  ![screen shot 2016-09-19 at 11 06 02 am](https://cloud.githubusercontent.com/assets/4099329/18622432/30cb6a98-7e59-11e6-9b07-d4a8277a7fce.png)
- [x] desain belum mengikuti tema yg baru

**Comment by budi7** [comment]
waktu bagikan via email, setelah input email lalu klik kirim tidak ada info sudah terkirim atau salah mengirim kode referal 
DUPLICATE #34

**Comment by budi7** [comment]
waktu inputkan redeem code yang terdaftar atau redeem code kepunyaan sendiri, tidak muncul sesuatu info atau notifikasi kalau error atau info gagal memasukkan redeem code 
DUPLICATE #35
