### ISSUE TITLE
auto login token API

### ISSUE THREAD

**Issue by agilma** [ThunderID/BALIN-WEB-V2#37]
- [x] auto login token ketika masih login error token expired

**Comment by chelsymooy** [comment]
mas @uchuy77 @budi7 yang ini udah ok
tlong di cek lagi ya

**Comment by budi7** [comment]
error terjadi juga di cc.balin.id
![screen shot 2016-10-07 at 1 37 29 pm](https://cloud.githubusercontent.com/assets/10555410/19180863/4f01db58-8c93-11e6-9f6c-16d7241e5503.png)

**Comment by budi7** [comment]
![screen shot 2016-10-07 at 5 43 27 pm](https://cloud.githubusercontent.com/assets/10555410/19187456/bd564860-8cb5-11e6-8241-4b050e9a0813.png)

**Comment by budi7** [comment]
Testing

**Comment by budi7** [comment]
tested no problem so far
