### ISSUE TITLE
[Mobile] Visitor Mendaftar ke balin

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#5]
CEK : https://trello.com/c/XVY2XA6K/192-14-visitor-mendaftar-ke-balin-via-phone
- Daftar By Email
- [x] Error message tidak tampil
- [x] Saya daftar sebagai Mrs, tapi jenis kelamin = pria (
  ![screenshot_2016-09-03-11-31-10](https://cloud.githubusercontent.com/assets/5895063/18222940/f5a492e4-71d0-11e6-9a7c-c5fc6fb6dda3.jpg)
  )
- [x] Pesan aneh (
  ![screenshot_2016-09-03-12-05-54](https://cloud.githubusercontent.com/assets/5895063/18222943/0981e85c-71d1-11e6-8eea-7ea1ed265c1a.jpg)
  )
- Claim Points (validate mail)
- [x] Apakah menu balin point akan menampilkan informasi point customer ? (Q)
- Daftar Via Invitation
- [x] Error message tidak tampil
- [ ] [PENDING] Setelah daftar menu berantakan (
  ![screenshot_2016-09-03-12-12-23](https://cloud.githubusercontent.com/assets/5895063/18222945/20d15aba-71d1-11e6-86dc-62bed81a1d17.jpg)
  )
- [x] [ENHANCEMENT] Email invitation kacaau (Q) (
  ![screenshot_2016-09-03-11-34-38](https://cloud.githubusercontent.com/assets/5895063/18222948/364207aa-71d1-11e6-9375-9dc9e1830ffa.jpg)
  )
- Redeem Code
- [x] Error message tidak tampil

**Comment by budi7** [comment]
[ENHANCEMENT] Email invitation kacaau (Q)  -> cont at #20
