### ISSUE TITLE
SSO Facebook

### ISSUE THREAD

**Issue by agilma** [ThunderID/BALIN-WEB-V2#50]
- [x] jika akun facebook belum login sebelumnya, halaman form login facebook tidak muncul keluar notif error
  ![screen shot 2016-09-26 at 9 12 50 am](https://cloud.githubusercontent.com/assets/4099329/18820844/41b3d922-83cb-11e6-8228-b23e6e086075.png)
- [x] jika akun facebook sudah login sebelumnya, muncul pesan error
  ![screen shot 2016-09-26 at 9 20 11 am](https://cloud.githubusercontent.com/assets/4099329/18821000/70a44068-83cc-11e6-9c6f-c79851d29880.png)

**Comment by chelsymooy** [comment]
mas @uchuy77 tolong di check redirect urlnya di apps balin di fb
