### ISSUE TITLE
Error veritrans

### ISSUE THREAD

**Issue by agilma** [ThunderID/BALIN-WEB-V2#51]
- [x] setelah pilih pembayaran menggunakan veritrans setelah checkout mendapatkan error Access denied due to unauthorized, tapi masuk profile lihat status transaksi checkout dan invoice terkirim ke email dan status checkout
  ![screen shot 2016-09-26 at 10 18 18 am](https://cloud.githubusercontent.com/assets/4099329/18821871/49e853da-83d4-11e6-81c4-18ed7f8e6ef2.png)

**Comment by chelsymooy** [comment]
invoice terkirim karena veritrans berfungsi untuk 'pembayaran', bukan 'checkout'
error 401 ku garap

**Comment by chelsymooy** [comment]
TJAKEP
![screenshot from 2016-09-27 08 48 56](https://cloud.githubusercontent.com/assets/5895063/18857581/4b1b0c3c-848f-11e6-9081-e73444d145ea.png)
