### ISSUE TITLE
Info Sign In

### ISSUE THREAD

**Issue by agilma** [ThunderID/BALIN-WEB-V2#52]
Info yang muncul tidak sesuai dgn errornya sewaktu login ![screen shot 2016-09-26 at 9 58 23 am](https://cloud.githubusercontent.com/assets/4099329/18821935/da061f88-83d4-11e6-9c87-a961f26184c8.png) 

setelah itu coba daftar ternyata email  sudah terdaftar 
![screen shot 2016-09-26 at 9 53 51 am](https://cloud.githubusercontent.com/assets/4099329/18821966/fff2b594-83d4-11e6-9281-aacc7b559cdb.png)

dan ternyata info yg harus muncul, adalah salah password

**Comment by chelsymooy** [comment]
errornya di frontend, pesan error yang dari api tdk ditampilkan

cc @uchuy77

**Comment by budi7** [comment]
@chelsymooy  balikan dari Api : user tidak ada utk case password salah
![screen shot 2016-09-28 at 11 21 55 am](https://cloud.githubusercontent.com/assets/10555410/18900652/e0f943d4-856d-11e6-8c2e-a930ea2c0e09.png)

**Comment by chelsymooy** [comment]
tadi udah ku pull dari server coba dicek @budi7

**Comment by budi7** [comment]
checked
