### ISSUE TITLE
[Mobile] Visitor login ke balin

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#6]
CEK : https://trello.com/c/0nX39JZD/204-26-customer-login-via-phone
- Facebook
- [x] Pada menu login tidak ada pilihan login
- Email
- [x] Tidak ada error message
- [x] Link lupa password berwarna hitam dan background super gelap (nyaris tak terlihat)

**Comment by budi7** [comment]
email : versi yg di test belum di gulp.
![screen shot 2016-09-05 at 1 55 49 pm](https://cloud.githubusercontent.com/assets/10555410/18239604/85e60f0e-7370-11e6-9833-54709168eb24.png)
