### ISSUE TITLE
[Mobile] Visitor menambahkan produk ke keranjang

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#7]
CEK : https://trello.com/c/6IUSR9RR/185-6-visitor-menambahkan-produk-ke-keranjang-via-phone
- Collection Detail
- [x] Q : Apakah jumlah item menunjuk pada total qty atau jenis barang? cc @budi7 
- [x] Tidak ada informasi item added
- [x] Link shopping bag not working here
- Cart Index
- [x] Kekeliruan promo price ! = diskon. Diskon = price - promo price ketika promo price > 0 (
  ![screenshot_2016-09-03-12-42-01](https://cloud.githubusercontent.com/assets/5895063/18223038/bf47c096-71d4-11e6-89cc-816116202fe7.jpg)
  )
- [x] Ketika mencapai stok maksimal warna tombol + tidak berubah (
  ![screenshot_2016-09-03-12-41-14](https://cloud.githubusercontent.com/assets/5895063/18223037/b7842d40-71d4-11e6-9597-8afdbf9ccc43.jpg)
  )

**Comment by budi7** [comment]
Fixed : Ketika mencapai stok maksimal warna tombol + tidak berubah
on : #15 - e990081

**Comment by budi7** [comment]
Fixed : Link shopping bag not working here
On : #15 - f9a20f9

**Comment by budi7** [comment]
Q : Apakah jumlah item menunjuk pada total qty atau jenis barang? cc @budi7
A : Jumlah Item

**Comment by budi7** [comment]
Fixed : Ketika mencapai stok maksimal warna tombol + tidak berubah
On : #17 - 92c1fdf
