### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by budi7** [ThunderID/BALIN-WEB-V2#77]
- [x] style landing page profile disamakan seperti product detail
- [x] nama user di str upper
- [x] dropdown info user seperti cart untuk desktop.
     isinya: general info user, latest transaction, logout, more -> link to landing page

**Comment by chelsymooy** [comment]
me here

**Comment by chelsymooy** [comment]
me not here

**Comment by budi7** [comment]
Checked : style landing page profile disamakan seperti product detail
done by @chelsymooy

**Comment by budi7** [comment]
doing
