### ISSUE TITLE
Product index

### ISSUE THREAD

**Issue by budi7** [ThunderID/BALIN-WEB-V2#78]
General
- [x] share button.
- [x] lazy load untuk image card. 
- [x] Filter produk tidak berlaku global tapi mengikuti kategori barang
- [x] filter warna kesulitan untuk menggunakan. tdk nampak perbedaan yg aktif dan tidak. 
- [x] Ajax url ganti judul halaman juga
- [x] animated gif sebagai loader saat ajax get product berlangsung

Desktop
- [x] desain filter dibuat menyerupai accordion product show. di mobile sudah bagus
- [x] sorting ux nya tidak kurang berasa saat di lakukan interaksi. sebaiknya diberkan efek hover warna lebih gelap.

Mobile
- [x] filter kategori digabung ke filter, lalu dibuat sticky on top
- [x] filter yang aktif tidak perlu ditampilkan semua, tapi cukup 2 atau 3 saja dan sisanya more ( jumlah filter aktif) 
- [x] nama filter tidak pakai (- atau _). gunakan pemisah yang lebih manusiawi

**Comment by chelsymooy** [comment]
- share button
- Filter produk tidak berlaku global tapi mengikuti kategori barang
