### ISSUE TITLE
[Mobile] Customer melakukan checkout

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-WEB-V2#8]
- [x] Link Kembali & Next tidak stabil (
  ![screenshot_2016-09-03-13-04-12](https://cloud.githubusercontent.com/assets/5895063/18223132/8d71e512-71d7-11e6-9de0-6f3be9bd99a2.jpg)
  )
- [x] Duplicate message (
  ![screenshot_2016-09-03-13-03-56](https://cloud.githubusercontent.com/assets/5895063/18223133/9343f84a-71d7-11e6-8753-a3afb450d39e.jpg)
  )

Potential cause : 
https://github.com/ThunderID/BALIN-WEB-V2/issues/2

**Comment by budi7** [comment]
DOING
