### ISSUE TITLE
Client Filter Error

### ISSUE THREAD

**Issue by budi7** [ThunderID/BALIN-WEB-V2#94]
![Uploading Screen Shot 2017-01-09 at 11.26.09 AM.png…]()

**Comment by chelsymooy** [comment]
Fixed @ 

https://github.com/ThunderID/BALIN-API-V2/commit/efaf7355566cf18c63d87c7085607815d7f3f95a

**Comment by chelsymooy** [comment]
Notes :
=> child or, parent and
